
DELETE http://localhost:8080/api/elements/delete/recycle_bin HTTP/1.1 
content-type: application/json

[
   {"name": "data_value", "item_id": "19","type": "Element", "parent_id": "15","parent": "project"}
]



